import os
import sys
import subprocess
import tempfile
import asyncio
import re
import queue
import threading
from app.config import settings
from app.utils.logger import logger

# Try imports
try:
    import sounddevice as sd
    from scipy.io import wavfile
    import numpy as np
except ImportError:
    sd = None
    wavfile = None
    logger.warning("sounddevice or scipy is not installed. Speech recording will be disabled.")

try:
    from gtts import gTTS
except ImportError:
    gTTS = None
    logger.warning("gtts is not installed. Text to speech will be disabled.")

try:
    import edge_tts
except ImportError:
    edge_tts = None
    logger.warning("edge-tts is not installed. Falling back to gTTS.")

# Global process tracking for queued playback
_playback_queue = queue.Queue()
_playback_thread = None
_stop_playback = False
_active_process = None
_is_currently_playing = False
_playback_epoch = 0


def is_speaking() -> bool:
    """
    Return True if the system is currently speaking/playing audio.
    """
    global _is_currently_playing
    return _is_currently_playing


def sanitize_for_speech(text: str) -> str:
    """
    Sanitize text for speech: remove Markdown symbols, emojis, hyphens, hashes,
    and format sentences for smooth human-like neural reading.
    """
    if not text:
        return ""

    # Remove disclaimers so the AI voice never speaks them
    disclaimers = [
        "This question is not in our database. The following answer is generated by AI based on general agricultural knowledge",
        "ಈ ಪ್ರಶ್ನೆಗೆ ನಮ್ಮ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ನೇರ ಉತ್ತರ ಲಭ್ಯವಿಲ್ಲ. ಕೆಳಗಿನ ಉತ್ತರವನ್ನು ಸಾಮಾನ್ಯ ಕೃಷಿ ಜ್ಞಾನದ ಆಧಾರದ ಮೇಲೆ AI ಮೂಲಕ ನೀಡಲಾಗಿದೆ",
        "This topic is not in our verified database — here is what Raitha Sathi knows from general agricultural knowledge",
        "ಈ ವಿಷಯ ನಮ್ಮ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ನೇರ ಇಲ್ಲ — ರೈತ ಸಾಥಿ ತನ್ನ ಸಾಮಾನ್ಯ ಕೃಷಿ ಜ್ಞಾನದಿಂದ ಉತ್ತರ ನೀಡುತ್ತಿದ್ದಾನೆ",
        "ಈ ವಿಷಯ ನಮ್ಮ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಇಲ್ಲ — ರೈತ ಸಾಥಿ ತನ್ನ ಸಾಮಾನ್ಯ ಕೃಷಿ ಜ್ಞಾನದಿಂದ ಉತ್ತರ ನೀಡುತ್ತಿದ್ದಾನೆ",
        "This topic is not in our verified database",
        "ಈ ಪ್ರಶ್ನೆಗೆ ನಮ್ಮ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ನೇರ ಉತ್ತರ ಲಭ್ಯವಿಲ್ಲ"
    ]
    for d in disclaimers:
        # Match case-insensitively and remove
        pattern = re.compile(re.escape(d), re.IGNORECASE)
        text = pattern.sub("", text)

    # Remove markdown heading symbols (e.g., #, ##, ###)
    text = re.sub(r'#+\s*', ' ', text)
    
    # Remove bullet points (e.g., -, *, •) at the start of lines or in text
    text = re.sub(r'^\s*[-*•]\s*', ' ', text, flags=re.MULTILINE)
    text = re.sub(r'\s+[-*•]\s+', ' ', text)
    
    # Remove Markdown inline formatting (bold, italic, code)
    text = text.replace("**", "").replace("*", "").replace("`", "").replace("_", "")
    
    # Remove hyperlinks [text](url) and raw brackets
    text = re.sub(r'\[.*?\]\(.*?\)', ' ', text)
    text = re.sub(r'\[.*?\]', ' ', text)
    
    # Keep only Kannada, alphanumeric characters, spaces, and standard punctuation (no emojis or raw symbols)
    cleaned = []
    for char in text:
        val = ord(char)
        # Kannada range: 0x0C80 to 0x0CFF
        # English letters, numbers, spaces, and basic punctuation
        if (0x0C80 <= val <= 0x0CFF) or char.isalnum() or char in " .,?!():;'\n":
            cleaned.append(char)
        else:
            cleaned.append(" ")
            
    text = "".join(cleaned)
    
    # Replace multiple spaces or newlines with a single space
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def _play_queue_worker():
    """
    Background worker that plays audio files sequentially from the queue.
    """
    global _active_process, _stop_playback
    while not _stop_playback:
        try:
            # Wait for next item in queue
            temp_file = _playback_queue.get(timeout=0.2)
        except queue.Empty:
            continue

        if _stop_playback:
            if temp_file and os.path.exists(temp_file):
                try:
                    os.remove(temp_file)
                except Exception:
                    pass
            break

        if temp_file and os.path.exists(temp_file):
            try:
                cmd = ["afplay", temp_file] if sys.platform == "darwin" else ["play", "-q", temp_file]
                global _is_currently_playing
                _is_currently_playing = True
                _active_process = subprocess.Popen(
                    cmd,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL
                )
                # Wait until current sentence completes playback
                _active_process.wait()
            except Exception as e:
                logger.error(f"Error during playback of {temp_file}: {e}")
            finally:
                _is_currently_playing = False
                # Clean up temp file immediately after playing
                try:
                    os.remove(temp_file)
                except Exception:
                    pass
                _playback_queue.task_done()


def stop_speech():
    """
    Stop the currently playing speech process, clear playback queues,
    and delete any pending temporary audio files.
    """
    global _playback_thread, _stop_playback, _active_process, _is_currently_playing
    _stop_playback = True
    _is_currently_playing = False
    
    # Terminate active process
    if _active_process:
        try:
            _active_process.terminate()
            _active_process.wait(timeout=0.1)
        except Exception:
            try:
                _active_process.kill()
            except Exception:
                pass
        _active_process = None

    # Drain queue and delete files
    while not _playback_queue.empty():
        try:
            temp_file = _playback_queue.get_nowait()
            if temp_file and os.path.exists(temp_file):
                os.remove(temp_file)
            _playback_queue.task_done()
        except Exception:
            pass

    # Stop thread
    if _playback_thread and _playback_thread.is_alive():
        _playback_thread.join(timeout=0.5)
    _playback_thread = None


def record_speech(filename="recorded_audio.wav", fs=16000) -> str:
    """
    Record audio from the default microphone in a non-blocking stream
    until the user presses Enter.
    Returns:
        'record': if audio was successfully recorded.
        'fallback': if recording packages are missing or failed.
        Any string typed by the user at the start prompt.
    """
    if sd is None or wavfile is None:
        logger.error("Recording packages (sounddevice/scipy) are missing.")
        return "fallback"

    try:
        if is_speaking():
            print("\n🎙️ [Voice Input] (AI is speaking...) Press [Enter] to interrupt & speak (or type question / 'text' / 'exit'): ", end="", flush=True)
        else:
            print("\n🎙️ [Voice Input] Press [Enter] to start speaking (or type question / 'text' / 'exit'): ", end="", flush=True)
        user_typed = input().strip()

        # If user typed something instead of hitting Enter, bypass recording and return it directly
        if user_typed:
            return user_typed

        # Stop speech again in case it started playing in the background
        stop_speech()

        print("🔴 Recording... Speak now. Press [Enter] when you are finished speaking.", end="", flush=True)

        audio_data = []

        def callback(indata, frames, time, status):
            if status:
                logger.warning(f"InputStream status: {status}")
            audio_data.append(indata.copy())

        # Start non-blocking input stream
        stream = sd.InputStream(samplerate=fs, channels=1, dtype='int16', callback=callback)
        with stream:
            input()  # Wait for user to hit Enter to stop

        print("🛑 Recording stopped.")

        if not audio_data:
            return "fallback"

        # Concatenate and save to WAV
        full_recording = np.concatenate(audio_data, axis=0)
        wavfile.write(filename, fs, full_recording)
        logger.info(f"Recorded audio saved to {filename}")
        return "record"
    except Exception as e:
        logger.error(f"Failed to record audio: {e}")
        print(f"⚠️ Could not record audio: {e}")
        return "fallback"


def devanagari_to_kannada(text: str) -> str:
    """
    Safely map any accidental Devanagari characters (0x0900-0x097F)
    to authentic Kannada script (0x0C80-0x0CFF).
    """
    out = []
    for ch in text:
        code = ord(ch)
        if 0x0900 <= code <= 0x097F:
            kn_code = code + 0x0380
            if 0x0C80 <= kn_code <= 0x0CFF:
                out.append(chr(kn_code))
            else:
                out.append(ch)
        else:
            out.append(ch)
    return "".join(out)


async def transcribe_speech(filename="recorded_audio.wav", language: str = None) -> str:
    """
    Transcribe the recorded audio file using the Gemini API.
    Strictly preserves Kannada script (ಕನ್ನಡ ಲಿಪಿ) when user speaks Kannada.
    """
    if not os.path.exists(filename):
        return ""

    if not settings.GEMINI_API_KEY:
        logger.error("GEMINI_API_KEY not configured for speech transcription.")
        return ""

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=settings.GEMINI_API_KEY)
        
        with open(filename, "rb") as f:
            audio_bytes = f.read()

        logger.info(f"Sending audio to Gemini for transcription (target language: {language or 'auto'})...")
        loop = asyncio.get_event_loop()
        
        if language == "kn":
            prompt = (
                "You are an expert speech-to-text transcription engine for Kannada (Raitha Sathi).\n"
                "The speaker is speaking in KANNADA.\n"
                "CRITICAL INSTRUCTIONS:\n"
                "1. Transcribe the spoken audio strictly into authentic KANNADA SCRIPT (ಕನ್ನಡ ಲಿಪಿ) only.\n"
                "   Example: If the speaker says 'Bharatada motta modala pradhana mantri yaru?', you MUST output 'ಭಾರತದ ಮೊಟ್ಟ ಮೊದಲ ಪ್ರಧಾನ ಮಂತ್ರಿ ಯಾರು?'.\n"
                "2. STRICTLY FORBIDDEN:\n"
                "   - NEVER output in Devanagari (Hindi) script under any circumstances.\n"
                "   - NEVER output in Latin/English alphabet (NO transliteration, NO Kanglish).\n"
                "   - NEVER translate the audio into English or any other language.\n"
                "3. If any standard English loan words or acronyms are used, transcribe them in Kannada script or standard acronyms.\n"
                "4. Do NOT answer the question. Do NOT add conversational replies or explanations.\n"
                "5. Output ONLY the verbatim transcribed Kannada text without quotes."
            )
        elif language == "en":
            prompt = (
                "You are an expert speech-to-text transcription engine for English (Raitha Sathi).\n"
                "The speaker is speaking in ENGLISH.\n"
                "CRITICAL INSTRUCTIONS:\n"
                "1. Transcribe the audio verbatim in English text.\n"
                "2. Do NOT translate into another language. Do NOT answer the question.\n"
                "3. Output ONLY the raw transcribed text without quotes."
            )
        else:
            prompt = (
                "You are an expert speech-to-text transcription engine for Kannada and English (Raitha Sathi).\n"
                "CRITICAL INSTRUCTIONS:\n"
                "1. If the speaker speaks in Kannada, transcribe STRICTLY in authentic KANNADA SCRIPT (ಕನ್ನಡ ಲಿಪಿ).\n"
                "   - NEVER output Kannada speech in Devanagari/Hindi script.\n"
                "   - NEVER output Kannada speech in Latin/English letters (NO Kanglish/transliteration).\n"
                "   - NEVER translate Kannada speech into English.\n"
                "2. If the speaker speaks in English, transcribe in English.\n"
                "3. Do NOT answer the question. Do NOT add comments or explanations.\n"
                "4. Output ONLY the verbatim transcribed text without quotes."
            )

        response = await loop.run_in_executor(
            None,
            lambda: client.models.generate_content(
                model=settings.GEMINI_MODEL,
                contents=[
                    types.Part.from_bytes(
                        data=audio_bytes,
                        mime_type="audio/wav",
                    ),
                    prompt
                ]
            )
        )
        
        transcription = response.text.strip() if response.text else ""
        
        # Strip extraneous quotes if Gemini wraps the response
        if transcription.startswith(('"', "'", "“")) and transcription.endswith(('"', "'", "”")):
            transcription = transcription[1:-1].strip()

        # If any Devanagari characters are present, convert to Kannada script
        has_devanagari = any(0x0900 <= ord(c) <= 0x097F for c in transcription)
        if has_devanagari or language == "kn":
            transcription = devanagari_to_kannada(transcription)

        logger.info(f"Speech transcription result: '{transcription}'")
        return transcription

    except Exception as e:
        logger.error(f"Failed to transcribe speech: {e}")
        return ""


def speak_text(text: str) -> bool:
    """
    Convert text to speech sentence-by-sentence.
    Downloads and queues sentences asynchronously, playing them instantly.
    """
    if gTTS is None:
        logger.warning("gTTS not installed. Skipping text-to-speech.")
        return False

    if not text:
        return False

    # Stop any currently playing speech before playing the new one
    stop_speech()

    global _playback_thread, _stop_playback, _playback_epoch
    _stop_playback = False
    _playback_epoch += 1
    current_epoch = _playback_epoch
    
    # Start playback worker thread
    _playback_thread = threading.Thread(target=_play_queue_worker, daemon=True)
    _playback_thread.start()

    # Do not split into sentences! Splitting into sentences causes afplay/network overhead 
    # and results in long, unnatural pauses. Generating the whole text at once is fast enough.
    sentences = [text]

    # Worker to download TTS files sequentially in the background
    def download_worker():
        for sentence in sentences:
            if _stop_playback or _playback_epoch != current_epoch:
                break
            
            cleaned_s = sanitize_for_speech(sentence)
            if not cleaned_s or len(cleaned_s.strip()) < 2:
                continue

            from app.utils.text_utils import detect_language
            lang = detect_language(cleaned_s)

            try:
                with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as f:
                    temp_filename = f.name
                
                if edge_tts is not None:
                    # The user wants ONE consistent Indian persona. 
                    # If the text is English, SapnaNeural struggles with meticulous pronunciation.
                    # We use NeerjaNeural (female, Indian English) to keep the same Indian female voice
                    # but with perfect, simple Indian English pronunciation.
                    if lang == "en":
                        # The user wants the English voice to sound EXACTLY like the Kannada voice, 
                        # so we use the identical voice model to ensure the same calm, grounded tone.
                        # We apply phonetic spelling fixes for common English words that Sapna mispronounces.
                        cleaned_s = re.sub(r'\band\b', 'aand', cleaned_s, flags=re.IGNORECASE)
                        cleaned_s = re.sub(r'\bor\b', 'ore', cleaned_s, flags=re.IGNORECASE)
                        
                        voice = "kn-IN-SapnaNeural"
                        communicate = edge_tts.Communicate(cleaned_s, voice, rate="-5%", pitch="-5Hz")
                    else:
                        voice = "kn-IN-SapnaNeural"
                        communicate = edge_tts.Communicate(cleaned_s, voice, rate="-5%", pitch="-5Hz")
                        
                    asyncio.run(communicate.save(temp_filename))
                else:
                    # Fallback to gTTS if edge-tts is not available
                    tts = gTTS(text=cleaned_s, lang=lang)
                    tts.save(temp_filename)
                
                if _stop_playback or _playback_epoch != current_epoch:
                    if os.path.exists(temp_filename):
                        os.remove(temp_filename)
                    break
                
                # Add to queue to play
                _playback_queue.put(temp_filename)
            except Exception as e:
                logger.error(f"Failed to generate TTS sentence: {e}")

    # Start download worker thread
    threading.Thread(target=download_worker, daemon=True).start()
    return True
